receivers:
  aerospike:
    endpoint: "aerospike:3000"
    collect_cluster_metrics: true
    collection_interval: 60s

  apache:
    endpoint: "http://apache:80/server-status?auto"
    collection_interval: 60s

  elasticsearch:
    endpoint: http://elasticsearch:9200
    username: elastic
    password: elastic
    collection_interval: 60s

  haproxy:
    endpoint: http://haproxy:8404/stats
    collection_interval: 60s
    metrics:
      haproxy.connections.total:
        enabled: true
      haproxy.failed_checks:
        enabled: true

  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
        exclude:
          devices:
            - ^loop.*$
          match_type: regexp
        metrics:
          system.disk.io:
            enabled: false
      filesystem:
        exclude_devices:
          devices:
            - ^/dev/loop.*$
          match_type: regexp
      memory:
      network:
        metrics:
          system.network.connections:
            enabled: false

  kafkametrics:
    protocol_version: "3.0.0"
    cluster_alias: my-kafka-cluster
    scrapers: [brokers, topics, consumers]
    brokers: kafka:9092
    collection_interval: 60s
    topic_match: ^[^_].*$
    resource_attributes:
      kafka.cluster.alias:
        enabled: true
    metadata:
      refresh_interval: 2m

  memcached:
    endpoint: memcached:11211
    transport: tcp
    collection_interval: 60s

  mysql:
    endpoint: mysql:3306
    username: root
    password: root
    collection_interval: 60s

  nginx:
    endpoint: http://nginx:80/status
    collection_interval: 60s

  postgresql:
    endpoint: postgres:5432
    username: cubeapm
    password: mypassword
    collection_interval: 60s
    tls:
      insecure: true

  rabbitmq:
    endpoint: http://rabbitmq:15672
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    collection_interval: 60s

processors:
  batch:
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: ["os"]

exporters:
  otlphttp:
    metrics_endpoint: http://host.docker.internal:3130/api/metrics/v1/save/otlp
    retry_on_failure:
      enabled: false

connectors:
  forward/aggregator:

service:
  pipelines:
    metrics:
      receivers:
        # - aerospike
        # - apache
        # - elasticsearch
        # - haproxy
        # - hostmetrics
        # - kafkametrics
        # - memcached
        - mysql
        - nginx
        # - postgresql
        # - rabbitmq
        # Receive from connector (which aggregates mongodb and redis pipelines)
        - forward/aggregator
      processors:
        - batch
        # - resourcedetection
      exporters:
        - otlphttp
